version: '3.4'

services:
  whisperspeech2text:
    image: whisperspeech2text
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - 8000:8000
    networks:
      - aicon
networks:
  aicon:
    driver: bridge

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
